-- Defining fixture for automatic pose adjustment
function setFixture()
  fixt = Image.Fixture.create()
  fixt:setReferencePose(teachPose)
  fixt:appendShape("outerCircle",outerCircle)
  fixt:appendShape("edgeRect1",edgeRect1)
  fixt:appendShape("edgeRect2",edgeRect2)
  fixt:appendShape("edgeRect3",edgeRect3)
  fixt:appendShape("edgeRect4",edgeRect4)
  fixt:appendShape("edgeRect5",edgeRect5)
  fixt:appendAngle("angle1",angle1)
  fixt:appendAngle("angle2",angle2)
  fixt:appendAngle("angle3",angle3)
  fixt:appendAngle("angle4",angle4)
  fixt:appendAngle("angle5",angle5)
  fixt:appendPoint("textPosRadius",textPosRadius)
  fixt:appendPoint("textPosDist1",textPosDist1)
  fixt:appendPoint("textPosDist2",textPosDist2)
  fixt:appendPoint("textPosIntersection",textPosIntersection)
  fixt:appendPoint("textPosAngle",textPosAngle)
end

-- Retrieving the pose-transformed shapes, angles and points
function getFixture()
  fixt:transform(poses[1])
  outerCircle = fixt:getShape("outerCircle")
  edgeRect1 = fixt:getShape("edgeRect1")
  edgeRect2 = fixt:getShape("edgeRect2")
  edgeRect3 = fixt:getShape("edgeRect3")
  edgeRect4 = fixt:getShape("edgeRect4")
  edgeRect5 = fixt:getShape("edgeRect5")
  angle1 = fixt:getAngle("angle1")
  angle2 = fixt:getAngle("angle2")
  angle3 = fixt:getAngle("angle3")
  angle4 = fixt:getAngle("angle4")
  angle5 = fixt:getAngle("angle5")
  textPosRadius = fixt:getPoint("textPosRadius") 
  textPosDist1 = fixt:getPoint("textPosDist1") 
  textPosDist2 = fixt:getPoint("textPosDist2") 
  textPosIntersection = fixt:getPoint("textPosIntersection") 
  textPosAngle = fixt:getPoint("textPosAngle")
end